### PR TITLE
GrammarLocation

### LINKED ISSUE #307: Relative offset for grammar source
In [peggy-test](https://github.com/hildjj/peggy-test) and [peggy-tag](https://github.com/peggyjs/peggy-tag), I'd like to be able to pass in a grammar location along with the grammar source, so that offset, line, and column in reported errors start at something other than zero.  This is useful when the grammar is embedded into a larger document, and only a portion of that larger document is passed into peggy.

Proposal:

- Add a `grammarLocation` to the API.  Carry it around all of the places `grammarSource` goes.  It will have the same shape as that returned by `location()` for easily passing it through from a wrapper grammar.  Only the `start` portion is likely to be used, however.
- Do not apply the offset until the very last moment, on output in `format`.  Otherwise the arrow pointing to the error will be in the wrong place.
- Default offsets are all zero.  Check for off-by-one errors in `line`, `column`, and `offset` of both `start` and `end`.

Compatibility:
- Will break anyone currently using `grammarLocation` as a parameter to their grammar.  We should document that the `grammar*` namespace is for internal use.

### PR DESCRIPTION
**Pull request by hildjj**
Fixes #307.

Adds a `GrammarLocation` class that can be used as your `grammarSource`, which specifies the offset of the grammar in a larger file.  Works for errors and source maps.

### CODE REVIEW

**Comment by hildjj** [comment]
Two example usages:

- In the upcoming peggy-test project: https://github.com/hildjj/peggy-test/blob/891e721093867145b681205fe606a93dbac1e5ce/lib/index.js#L120
- In the upcoming peggy-tag project: https://github.com/hildjj/peggy-tag/blob/bb0f8a1bb778c3e31a6a62ea35e1a052fce84ac1/lib/index.js#L25

File: lib/compiler/passes/generate-js.js [hunk 1]
```diff
@@ -707,16 +707,19 @@ function generateJS(ast, options) {
...
       "      var e = this.location.end;",
-      "      var filler = peg$padEnd(\"\", s.line.toString().length, ' ');",
+      "      var filler = peg$padEnd(\"\", offset_s.line.toString().length, ' ');",
       "      var line = src[s.line - 1];",
       "      var last = s.line === e.line ? e.column : line.length + 1;",
       "      var hatLen = (last - s.column) || 1;",
       "      str += \"\\n --> \" + loc + \"\\n\"",
       "          + filler + \" |\\n\"",
-      "          + s.line + \" | \" + line + \"\\n\"",
+      "          + offset_s.line + \" | \" + line + \"\\n\"",
```
Comment (tornikeshavishvili) [inline lib/compiler/passes/generate-js.js:725]: Would it be better to retrieve newline characters from NodeJS environment itself?

**Comment by tornikeshavishvili** [comment]
I just thinking, to better understand project structure, it would be nice to have graphical representation of its component parts with a simple block scheme or something like this?

**Comment by hildjj** [comment]
> I was just thinking, to better understand project structure, it would be nice to have graphical representation of its component parts with a simple block scheme or something like this?

Probably a good idea.  Please create an issue with anything that isn't clear to you.  Whatever confusion you are willing to share will help me figure out which direction to tackle this.

File: lib/compiler/passes/generate-js.js (hunk 1 above)
Comment (hildjj) [reply lib/compiler/passes/generate-js.js:725]: We don't have access to the node environment here.  This is generated es5 JS that needs to be able to run in the browser also.  We could add an optional second parameter that is the line endings to use, then pass in node's `os.EOL` when calling this code from the CLI.  However, since this is an existing problem not related to this change, I'll start a new bug for us to discuss this.

Comment (hildjj) [reply lib/compiler/passes/generate-js.js:725]: See #320

Comment (tornikeshavishvili) [reply lib/compiler/passes/generate-js.js:725]: I see. In my opinion, it should be possible to live the implementation as is at this point :|
